Task/1 migrate utilities
Godlike/Mule pull request #2
Opened 2018-02-14 00:33 UTC by dsodintsov

Most of the pull request is straight migration of utilities from Unicorn repo. The rest is configuration releated.

2018-02-15 13:35 UTC, ilia-glushchenko requested changes

2018-02-15 13:35 UTC, ilia-glushchenko commented on MuleUtilities/MuleVersionInfo.rc.in
> +#include <Windows.h>
Copyrights?

2018-02-17 20:16 UTC, dsodintsov commented on MuleUtilities/MuleVersionInfo.rc.in
> +#include <Windows.h>
Done

2018-02-17 21:34 UTC, ilia-glushchenko commented
Adding issue indices to the commit messages probably going to be a good thing as well.

2018-02-17 23:01 UTC, dsodintsov commented
Done

2018-02-17 23:02 UTC, ilia-glushchenko approved these changes

2018-02-18 17:32 UTC, krupitskas approved these changes

2018-02-18 17:33 UTC, merged