Task 3/logging subsystem
Godlike/Mule pull request #4
Opened 2018-02-21 07:01 UTC by dsodintsov

2018-02-22 23:29 UTC, ilia-glushchenko requested changes

2018-02-22 23:29 UTC, ilia-glushchenko commented on MuleUtilities/asset/source/SimpleStorage.cpp
> +        g_loggers[Log::mule_storage]->Debug("Requested asset \"{}\" -> exists", key.c_str());
For me, it looks way too long, maybe add some alias or typedef or something?

2018-02-22 23:29 UTC, ilia-glushchenko commented on MuleUtilities/source/Logger.cpp
> +    ,
Move it to the previous line?

2018-02-23 03:48 UTC, dsodintsov commented on MuleUtilities/asset/source/SimpleStorage.cpp
> +        g_loggers[Log::mule_storage]->Debug("Requested asset \"{}\" -> exists", key.c_str());
Added macros

2018-02-23 03:48 UTC, dsodintsov commented on MuleUtilities/source/Logger.cpp
> +    ,
Reformatted this bit

2018-02-23 10:15 UTC, ilia-glushchenko commented
Is there any particular reason why Fix clang warning commit does not have issue reference?

2018-02-23 10:21 UTC, krupitskas commented
Squash and merge, anyway we havent here any pullaprove setup

2018-02-23 16:14 UTC, dsodintsov commented
`Is there any particular reason why Fix clang warning commit does not have issue reference?`

Generally non-functional commits that are subject to be squashed will create garbage unneeded references in the issue itself. It's better to have functional commits there than random ones.

2018-02-23 16:16 UTC, ilia-glushchenko commented
Okay, as long as they don't go to master, I'm good with it.

2018-02-23 16:16 UTC, ilia-glushchenko approved these changes

2018-02-24 01:04 UTC, merged